name: Cucumber

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: install ruby
        run: sudo apt-get install ruby-full

      - name: install bundler
        run: sudo gem install bundler

      - name: sudo bundle install
        run: sudo bundle install

      - name: cucumber generate report.html
        run: cucumber API_KEY=${{ secrets.API_KEY }} --publish-quiet -f html > report.html

      - name: copy report.html to _site directory
        run: cp report.html index.html report/

          

      

          

     
