name: Cucumber

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: test var print
        run: echo "${{ secrets.API_KEY }}"

      - name: install ruby
        run: sudo apt-get install ruby-full

      - name: install bundler
        run: sudo gem install bundler

      - name: sudo bundle install
        run: sudo bundle install

      - name: cucumber
        run: cucumber API_KEY=${{ github.API_KEY }}

      #- name: cucumber --publish-quiet -f html > report.html
      #  run: cucumber --publish-quiet -f html > report.html

          

     
