name: Cucumber

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: install ruby
        run: sudo apt-get install ruby-full

      - name: install bundler
        run: sudo gem install bundler

      - name: bundle install
        run: sudo bundle install

      - name: cucumber
        run: cucumber

      #- name: cucumber --publish-quiet -f html > report.html
      #  run: cucumber --publish-quiet -f html > report.html

      - name: ls
        run: ls
          

     
