name: Cucumber

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          bundler-cache: true
        
      - name: install ruby
        run: sudo apt-get install ruby-full
        env:
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

      - name: install bundler
        run: sudo gem install bundler

      - name: sudo bundle install
        run: sudo bundle install

      - name: cucumber --publish
        run: cucumber API_KEY=${{ secrets.API_KEY }} --publish
        
     
            

          

     
