name: Cucumber

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: install ruby
        run: sudo apt-get install ruby-full

      - name: install bundler
        run: sudo gem install bundler

      - name: sudo bundle install
        run: sudo bundle install

      - name: cucumber generate report.html
        run: cucumber API_KEY=${{ secrets.API_KEY }} --publish-quiet -f html > report.html

      - name: Git commit, pull & push action

        uses: mgrybyk/git-commit-pull-push-action@v1.2.3
        with:
          # Local file path to the git repository. Defaults to the current directory '.'
          repository: .
          # Git branch name, where changes should be pushed to.
          branch: main
          # Commit message
          commit_message: Adding report.html
          # git add arguments (eg. -u) or 'src/*.js'
          add_args: report.html
                
      
                
      
            

          

     
